name: Deploy EricMinimalApi to Docker hub then Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    environment: MinimalApiEnv
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      # grep the version from ./EricMinimalApi/appsettings.json, var AppVersion = "1.0.0", then cut the version number between the double quotes
      - name: "Get version"
        id: get_version
        run: echo "APP_VERSION=$(jq -r '.AppVersion' ./EricMinimalApi/appsettings.json)" >> $GITHUB_ENV

      - name: "Login via Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile-EricMinimalApi
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/ericminimalapi:latest, ${{ env.DOCKER_HUB_USERNAME }}/ericminimalapi:${{ env.APP_VERSION }}

  deploy-to-azure:
    needs: build-and-push-to-docker-hub
    runs-on: ubuntu-latest

    steps:
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "EricMinimalApi"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          images: ${{ env.DOCKER_HUB_USERNAME }}/ericminimalapi:latest
