name: Deploy EricControllerBasedApi to Docker hub then Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    environment: ControllerBasedApiEnv
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      # grep the version from ./EricControllerBasedApi/appsettings.json
      - name: "Get version"
        id: get_version
        run: echo "APP_VERSION=$(jq -r '.AppVersion' ./src/EricControllerBasedApi/appsettings.json)" >> $GITHUB_ENV

      - name: "Login via Docker Hub"
        uses: docker/login-action@v2
        with:
          username: "onlineeric"
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile-EricControllerBasedApi
          push: true
          tags: onlineeric/ericcontrollerbasedapi:latest, onlineeric/ericcontrollerbasedapi:${{ env.APP_VERSION }}

  deploy-to-azure:
    needs: build-and-push-to-docker-hub
    runs-on: ubuntu-latest
    environment: ControllerBasedApiEnv

    steps:
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "EricControllerBasedApi"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          images: onlineeric/ericcontrollerbasedapi:latest
